language: php

php:
  - 5.3
  - 5.4

env:
  - MONGO_VERSION=1.2.12

services: mongodb

before_script:
  - pecl -q install mongo-${MONGO_VERSION} && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install --dev

script: phpunit --coverage-text -c tests/

notifications:
  email:
    - gediminas.morkevicius@gmail.com
